name: Run Tests on Feature Branch

on:
  push:
    branches:
      - 23March   # Runs only on 'feature-branch'
  pull_request:
    branches:
      - main             # Runs when PR is made to 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests on feature-branch!"
